insert into public.prompts (x_axis_label, y_axis_label, source) values
  ('Would survive a zombie apocalypse', 'Would cause a zombie apocalypse', 'curated'),
  ('Would bail you out of jail', 'Would be the reason you''re in jail', 'curated'),
  ('Good at keeping secrets', 'Has the most secrets', 'curated'),
  ('Would trust with your phone unlocked', 'Would go through your phone', 'curated'),
  ('Most likely to become famous', 'Most likely to become infamous', 'curated'),
  ('Best road trip companion', 'Worst backseat driver', 'curated'),
  ('Would share their last slice of pizza', 'Would steal your pizza', 'curated'),
  ('Most punctual', 'Most likely to cancel last minute', 'curated'),
  ('Best wingman/wingwoman', 'Biggest cockblock', 'curated'),
  ('Would help you move apartments', 'Would pretend to be busy', 'curated'),
  ('Best cook in the group', 'Would burn water', 'curated'),
  ('Most adventurous', 'Biggest homebody', 'curated'),
  ('Would survive alone on a desert island', 'Would cry first', 'curated'),
  ('Best at giving advice', 'Gives the worst advice', 'curated'),
  ('Most likely to go viral on TikTok', 'Most likely to be a meme', 'curated'),
  ('Would trust to plan your wedding', 'Would ruin the toast', 'curated'),
  ('Most emotionally intelligent', 'Most emotionally chaotic', 'curated'),
  ('Best person to call at 3 AM', 'Most likely to BE calling at 3 AM', 'curated'),
  ('Would take a bullet for you', 'Would use you as a human shield', 'curated'),
  ('Most responsible with money', 'Most likely to blow a paycheck in a day', 'curated'),
  ('Best karaoke partner', 'Should never touch a microphone', 'curated'),
  ('Would be the best teacher', 'Would be sent to the principal''s office', 'curated'),
  ('Most likely to win a bar fight', 'Most likely to start a bar fight', 'curated'),
  ('Best dressed in the group', 'Most questionable fashion choices', 'curated'),
  ('Would trust to babysit your kids', 'Would teach your kids bad words', 'curated'),
  ('Most book smart', 'Most street smart', 'curated'),
  ('Best listener', 'Biggest interrupter', 'curated'),
  ('Would survive a horror movie', 'Would die first in a horror movie', 'curated'),
  ('Most competitive', 'Most chill about losing', 'curated'),
  ('Would share their Netflix password', 'Would mooch off everyone else', 'curated'),
  ('Most likely to become president', 'Most likely to start a conspiracy theory', 'curated'),
  ('Best travel buddy', 'Most likely to lose their passport', 'curated');
